# Dev Environment Properties
# MongoDB Configuration
spring.data.mongodb.uri=${MONGODB_URI:mongodb://localhost:27017}
spring.data.mongodb.database=clinic_management

# Server
server.port=${SERVER_PORT:8080}

# JWT Properties
jwt.secret=${JWT_SECRET:8a846c429340f1a6fa029f605a960df768f54c126e3c50f839a83424d9e03d42b918115cc7b2f676bc1050e933454238}
jwt.expiration=${JWT_EXPIRATION:86400000}

# CORS
cors.allowed.origins=${CORS_ALLOWED_ORIGINS:*}
