# Prod Environment Properties

# MongoDB Configuration
spring.data.mongodb.uri=mongodb://localhost:27017/clinic_management

# Server
server.port=8080

# JWT Properties
jwt.secret=8a846c429340f1a6fa029f605a960df768f54c126e3c50f839a83424d9e03d42b918115cc7b2f676bc1050e933454238
jwt.expiration=86400000

# CORS
cors.allowed.origins=*

# Application Name
spring.application.name=clinic-management

# Logging Configuration
logging.file.path=logs
