# Application Properties
spring.application.name=clinic-management

# Active Profile
spring.profiles.active=${SPRING_PROFILES_ACTIVE:dev}

# Jackson / Serialization
spring.jackson.default-property-inclusion=non_null

# Springdoc / Swagger
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
